language: java
 
os:
  - linux
 
jdk:
  - oraclejdk8
 
script: "mvn cobertura:cobertura"
   
after_success:
  - bash <(curl -s https://cov.lanlytics.com/bash) -t 90d7b191-2bb6-444a-bf6f-3d602cef9d10 
